export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const MY_POKEDEX = 'MY_POKEDEX';
export const CAPTURE_POKEMON = 'CAPTURE_POKEMON';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';
export const SEARCH_TERM_UPDATED = 'SEARCH_TERM_UPDATED';
